services:
  - type: web
    name: foodhero
    env: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: cd ../client && npm install && npm run build && cd ../server && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false        # set manually in Render dashboard
      - key: JWT_SECRET
        sync: false        # set manually in Render dashboard
      - key: GOOGLE_CLIENT_ID
        sync: false        # set manually in Render dashboard
      - key: GOOGLE_CLIENT_SECRET
        sync: false        # set manually in Render dashboard
      - key: CLIENT_URL
        sync: false        # set to your Render app URL e.g. https://foodhero.onrender.com
